wallpaper {
    monitor = eDP-1
    path =  ~/Documents/wallpaper/wallpaper_dark.jpg
    fit_mode = cover
  }

wallpaper {
    monitor =
    path = ~/Documents/wallpaper/wallpaper_dark.jpg
    fit_mode = cover
  }
